apiVersion: v1
kind: Service
metadata:
  name: capstone-udacity
spec:
  selector:
    app: capstone-udacity
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-udacity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: capstone-udacity
  template:
    metadata:
      labels:
        app: capstone-udacity
    spec:
      containers:
        - name: capstone-udacity
          image: veeravee93/capstone
          imagePullPolicy: "Always"
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "1024Mi"
              cpu: "500m"
